name: image-analysis
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - jupyterlab
  - nb_conda_kernels
  - napari
  - cellfinder-napari
  - brainreg-napari
  - keras
  - dask
  - numpy
  - scipy
  - tifffile
  - pooch
  - tqdm